All the things.

diff --git a/bin/certs b/bin/certs
--- a/bin/certs
+++ b/bin/certs
@@ -6,6 +6,14 @@ if [ ! -d "$ROOT_DIR/config/ssl" ]; then
   mkdir -p "$ROOT_DIR/config/ssl"
 fi
 
+ENV_FILE="${ROOT_DIR}/.env"
+./bin/log "INFO" "Checking .env file exists in ${ENV_FILE}"
+if [ ! -f "${ENV_FILE}" ]; then
+  ./bin/log "ERROR" "No .env file found"
+  exit 1;
+fi
+source "${ENV_FILE}";
+
 ./bin/log "INFO" "Running mkcert to generate certificates for local domains..."
-mkcert -cert-file ./config/ssl/local-cert.pem -key-file ./config/ssl/local-key.pem "ecigintelligence.local" "*.ecigintelligence.local" "tobaccointelligence.local" "*.tobaccointelligence.local" "cannintelligence.local" "*.cannintelligence.local" "tamarindintelligence.local" "*.tamarindintelligence.local" 127.0.0.1
+mkcert -cert-file ./config/ssl/local-cert.pem -key-file ./config/ssl/local-key.pem $APP_DOMAINS 127.0.0.1
 sudo mkcert -install
