Remove unncessary files.

diff --git a/bin/wp b/bin/wp
--- a/bin/wp
+++ b/bin/wp
@@ -1,31 +1,33 @@
 #!/bin/bash
 ROOT_DIR=$(pwd)
 YML_FILE="${ROOT_DIR}/wp-cli.yml"
+ENV_FILE="${ROOT_DIR}/.env"
 
-if [[ "$1" == @* ]]; then
-    ALIAS="${1#@}"
-    shift
+if [ ! -f $ENV_FILE ]; then
+  ./bin/log "ERROR" "No .env file found"
+  exit 1;
+fi
 
-    if [ ! -f "$YML_FILE" ]; then
-        ./bin/log "ERROR" "wp-cli.yml not found in $(pwd)"
-        exit 1
-    fi
+source "${ENV_FILE}"
+ALIAS="${SITE_SLUG}"
 
-    CONTAINER_NAME=$(grep -A 1 "@$ALIAS:" "$YML_FILE" | grep 'ssh:' | sed -E 's/.*@([^ ]+).*/\1/')
-
-    if [ -z "$CONTAINER_NAME" ]; then
-        ./bin/log "ERROR" "Alias @$ALIAS not found in $YML_FILE"
-        exit 1
-    fi
-
-    if [ -t 0 ]; then
-        TTY_FLAG="-it"
-    else
-        TTY_FLAG="-i"
-    fi
-    ./bin/log "INFO" "Running wp $* in container $CONTAINER_NAME"
-    docker exec $TTY_FLAG -u www-data "$CONTAINER_NAME" wp "$@"
-else
-    ./bin/log "ERROR" "This wrapper requires a site alias (e.g., wp @ei <command>)"
+if [ ! -f "$YML_FILE" ]; then
+    ./bin/log "ERROR" "wp-cli.yml not found in $(pwd)"
     exit 1
 fi
+
+CONTAINER_NAME=$(grep -A 1 "@$ALIAS:" "$YML_FILE" | grep 'ssh:' | sed -E 's/.*@([^ ]+).*/\1/')
+
+if [ -z "$CONTAINER_NAME" ]; then
+    ./bin/log "ERROR" "Alias @$ALIAS not found in $YML_FILE"
+    exit 1
+fi
+
+if [ -t 0 ]; then
+    TTY_FLAG="-it"
+else
+    TTY_FLAG="-i"
+fi
+./bin/log "INFO" "Running wp $* in container $CONTAINER_NAME"
+./bin/log "INFO" "${ALIAS}"
+docker exec $TTY_FLAG -u www-data "$CONTAINER_NAME" wp "$@"
